<?php

$latin1array = array(

//&iexcl;|&cent;|&pound;|&curren;|&yen;|&brvbar;|&sect;|&uml;|&copy;|&ordf;|&laquo;|&not;|&shy;|&reg;|&macr;|&deg;|&plusmn;|&sup2;|&sup3;|&acute;|&micro;|&para;|&middot;|&cedil;|&sup1;|&ordm;|&raquo;|&frac14;|&frac12;|&frac34;|&iquest;|&Agrave;|&Aacute;|&Acirc;|&Atilde;|&Auml;|&Aring;|&AElig;|&Ccedil;|&Egrave;|&Eacute;|&Ecirc;|&Euml;|&Igrave;|&Iacute;|&Icirc;|&Iuml;|&ETH;|&Ntilde;|&Ograve;|&Oacute;|&Ocirc;|&Otilde;|&Ouml;|&times;|&Oslash;|&Ugrave;|&Uacute;|&Ucirc;|&Uuml;|&Yacute;|&THORN;|&szlig;|&agrave;|&aacute;|&acirc;|&atilde;|&auml;|&aring;|&aelig;|&ccedil;|&egrave;|&eacute;|&ecirc;|&euml;|&igrave;|&iacute;|&icirc;|&iuml;|&eth;|&ntilde;|&ograve;|&oacute;|&ocirc;|&otilde;|&ouml;|&divide;|&oslash;|&ugrave;|&uacute;|&ucirc;|&uuml;|&yacute;|&thorn;|&yuml;

// raw, decimal, hexadecimal, named
array("¡", "&#161;", "&#xa1;", "&iexcl;"),
array("¢", "&#162;", "&#xa2;", "&cent;"),
array("£", "&#163;", "&#xa3;", "&pound;"),
array("¤", "&#164;", "&#xa4;", "&curren;"),
array("¥", "&#165;", "&#xa5;", "&yen;"),
array("¦", "&#166;", "&#xa6;", "&brvbar;"),
array("§", "&#167;", "&#xa7;", "&sect;"),
array("¨", "&#168;", "&#xa8;", "&uml;"),
array("©", "&#169;", "&#xa9;", "&copy;"),
array("ª", "&#170;", "&#xaa;", "&ordf;"),
array("«", "&#171;", "&#xab;", "&laquo;"),
array("¬", "&#172;", "&#xac;", "&not;"),
array("­", "&#173;", "&#xad;", "&shy;"),
array("®", "&#174;", "&#xae;", "&reg;"),
array("¯", "&#175;", "&#xaf;", "&macr;"),
array("°", "&#176;", "&#xb0;", "&deg;"),
array("±", "&#177;", "&#xb1;", "&plusmn;"),
array("²", "&#178;", "&#xb2;", "&sup2;"),
array("³", "&#179;", "&#xb3;", "&sup3;"),
array("´", "&#180;", "&#xb4;", "&acute;"),
array("µ", "&#181;", "&#xb5;", "&micro;"),
array("¶", "&#182;", "&#xb6;", "&para;"),
array("·", "&#183;", "&#xb7;", "&middot;"),
array("¸", "&#184;", "&#xb8;", "&cedil;"),
array("¹", "&#185;", "&#xb9;", "&sup1;"),
array("º", "&#186;", "&#xba;", "&ordm;"),
array("»", "&#187;", "&#xbb;", "&raquo;"),
array("¼", "&#188;", "&#xbc;", "&frac14;"),
array("½", "&#189;", "&#xbd;", "&frac12;"),
array("¾", "&#190;", "&#xbe;", "&frac34;"),
array("¿", "&#191;", "&#xbf;", "&iquest;"),
array("À", "&#192;", "&#xc0;", "&Agrave;"),
array("Á", "&#193;", "&#xc1;", "&Aacute;"),
array("Â", "&#194;", "&#xc2;", "&Acirc;"),
array("Ã", "&#195;", "&#xc3;", "&Atilde;"),
array("Ä", "&#196;", "&#xc4;", "&Auml;"),
array("Å", "&#197;", "&#xc5;", "&Aring;"),
array("Æ", "&#198;", "&#xc6;", "&AElig;"),
array("Ç", "&#199;", "&#xc7;", "&Ccedil;"),
array("È", "&#200;", "&#xc8;", "&Egrave;"),
array("É", "&#201;", "&#xc9;", "&Eacute;"),
array("Ê", "&#202;", "&#xca;", "&Ecirc;"),
array("Ë", "&#203;", "&#xcb;", "&Euml;"),
array("Ì", "&#204;", "&#xcc;", "&Igrave;"),
array("Í", "&#205;", "&#xcd;", "&Iacute;"),
array("Î", "&#206;", "&#xce;", "&Icirc;"),
array("Ï", "&#207;", "&#xcf;", "&Iuml;"),
array("Ð", "&#208;", "&#xd0;", "&ETH;"),
array("Ñ", "&#209;", "&#xd1;", "&Ntilde;"),
array("Ò", "&#210;", "&#xd2;", "&Ograve;"),
array("Ó", "&#211;", "&#xd3;", "&Oacute;"),
array("Ô", "&#212;", "&#xd4;", "&Ocirc;"),
array("Õ", "&#213;", "&#xd5;", "&Otilde;"),
array("Ö", "&#214;", "&#xd6;", "&Ouml;"),
array("×", "&#215;", "&#xd7;", "&times;"),
array("Ø", "&#216;", "&#xd8;", "&Oslash;"),
array("Ù", "&#217;", "&#xd9;", "&Ugrave;"),
array("Ú", "&#218;", "&#xda;", "&Uacute;"),
array("Û", "&#219;", "&#xdb;", "&Ucirc;"),
array("Ü", "&#220;", "&#xdc;", "&Uuml;"),
array("Ý", "&#221;", "&#xdd;", "&Yacute;"),
array("Þ", "&#222;", "&#xde;", "&THORN;"),
array("ß", "&#223;", "&#xdf;", "&szlig;"),
array("à", "&#224;", "&#xe0;", "&agrave;"),
array("á", "&#225;", "&#xe1;", "&aacute;"),
array("â", "&#226;", "&#xe2;", "&acirc;"),
array("ã", "&#227;", "&#xe3;", "&atilde;"),
array("ä", "&#228;", "&#xe4;", "&auml;"),
array("å", "&#229;", "&#xe5;", "&aring;"),
array("æ", "&#230;", "&#xe6;", "&aelig;"),
array("ç", "&#231;", "&#xe7;", "&ccedil;"),
array("è", "&#232;", "&#xe8;", "&egrave;"),
array("é", "&#233;", "&#xe9;", "&eacute;"),
array("ê", "&#234;", "&#xea;", "&ecirc;"),
array("ë", "&#235;", "&#xeb;", "&euml;"),
array("ì", "&#236;", "&#xec;", "&igrave;"),
array("í", "&#237;", "&#xed;", "&iacute;"),
array("î", "&#238;", "&#xee;", "&icirc;"),
array("ï", "&#239;", "&#xef;", "&iuml;"),
array("ð", "&#240;", "&#xf0;", "&eth;"),
array("ñ", "&#241;", "&#xf1;", "&ntilde;"),
array("ò", "&#242;", "&#xf2;", "&ograve;"),
array("ó", "&#243;", "&#xf3;", "&oacute;"),
array("ô", "&#244;", "&#xf4;", "&ocirc;"),
array("õ", "&#245;", "&#xf5;", "&otilde;"),
array("ö", "&#246;", "&#xf6;", "&ouml;"),
array("÷", "&#247;", "&#xf7;", "&divide;"),
array("ø", "&#248;", "&#xf8;", "&oslash;"),
array("ù", "&#249;", "&#xf9;", "&ugrave;"),
array("ú", "&#250;", "&#xfa;", "&uacute;"),
array("û", "&#251;", "&#xfb;", "&ucirc;"),
array("ü", "&#252;", "&#xfc;", "&uuml;"),
array("ý", "&#253;", "&#xfd;", "&yacute;"),
array("þ", "&#254;", "&#xfe;", "&thorn;"),
array("ÿ", "&#255;", "&#xff;", "&yuml;"),

);

?>